Repository stwebcode/register, pull requests merged in 2021-03, with the labels that each got.

#19 add header/footer and index
  footer.php
  header.php
  images/logo.png
  index.css
  index.php
Labels: enhancement

#20 evo-calendar implementācija
  .gitignore
  ajax.sql
  calendar/evo-calendar.css
  calendar/evo-calendar.js
  calendar/evo-calendar.midnight-blue.css
  database_manager.php
  header.php
  index.css
  index.php
  login.php
  register.php
  server.php
Labels: Security Risk, enhancement

#22 Event izveide, sava kursa notikumu skatīšana
  ajax.sql
  database_manager.php
  server.php
Labels: enhancement

#24 Salaboju login kļūdu neizvadīšanu
  server.php
Labels: HOTFIX

#25 Responsīvas navigācijas ieviešana
  calendar/evo-calendar.css
  calendar/evo-calendar.midnight-blue.css
  footer.php
  header.php
  index.css
Labels: enhancement
